name: ESLint Linting

on:
  push:
    paths:
      - 'services/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './services/score-service/package-lock.json'
        
    - name: Install dependencies
      run: npm install
      working-directory: ./services/score-service
      
    - name: Run ESLint
      run: npm run lint
      working-directory: ./services/score-service 